language: node_js
node_js:
    - "8"
    - "10"
services:
    - mongodb
    - mysql
    - postgresql
addons:
    mariadb: '10.1'
before_install:
    - mysql -e 'CREATE DATABASE urungi_tests'
    - mysql -e 'GRANT ALL ON urungi_tests.* TO urungi@localhost IDENTIFIED BY "urungi"'
    - psql -c 'create database urungi_tests;' -U postgres
    - npm i -g npm
cache: npm
