language: node_js
node_js:
    - "lts/*"
services:
    - mongodb
    - mysql
addons:
    mariadb: '10.1'
before_install:
    - mysql -e 'CREATE DATABASE urungi_tests'
    - mysql -e 'GRANT ALL ON urungi_tests.* TO urungi@localhost IDENTIFIED BY "urungi"'
    - npm i -g npm
install:
    - npm ci
cache:
    directories:
        - "$HOME/.npm"
script:
    - npm test
