version: '3'
services:
    web:
        build: .
        ports:
            - 8080:8080
        depends_on:
            - mongo
        environment:
            - MONGODB_URI=mongodb://mongo:27017/urungi_development
    mongo:
        image: mongo:3.6-xenial
        ports:
            - 27017:27017
